<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net9.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>

		<ApplicationIcon>Image\ParasiteReplayAnalyzer.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\ParasiteZetaReplayAnalyzer\SC2ReplayParasiteAnalyzer.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Image\parasiteloadpic.png" />
	</ItemGroup>

</Project>